pub fn recite(start_bottles: u32, take_down: u32) -> String {
    let bottle_song = concat!(
            "Ten green bottles hanging on the wall,\n",
            "Ten green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be nine green bottles hanging on the wall.\n",
            "\n",
            "Nine green bottles hanging on the wall,\n",
            "Nine green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be eight green bottles hanging on the wall.\n",
            "\n",
            "Eight green bottles hanging on the wall,\n",
            "Eight green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be seven green bottles hanging on the wall.\n",
            "\n",
            "Seven green bottles hanging on the wall,\n",
            "Seven green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be six green bottles hanging on the wall.\n",
            "\n",
            "Six green bottles hanging on the wall,\n",
            "Six green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be five green bottles hanging on the wall.\n",
            "\n",
            "Five green bottles hanging on the wall,\n",
            "Five green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be four green bottles hanging on the wall.\n",
            "\n",
            "Four green bottles hanging on the wall,\n",
            "Four green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be three green bottles hanging on the wall.\n",
            "\n",
            "Three green bottles hanging on the wall,\n",
            "Three green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be two green bottles hanging on the wall.\n",
            "\n",
            "Two green bottles hanging on the wall,\n",
            "Two green bottles hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be one green bottle hanging on the wall.\n",
            "\n",
            "One green bottle hanging on the wall,\n",
            "One green bottle hanging on the wall,\n",
            "And if one green bottle should accidentally fall,\n",
            "There'll be no green bottles hanging on the wall.",
        );

    let bottle_song_collection = bottle_song.split("\n\n").collect::<Vec<_>>();

    bottle_song_collection[(bottle_song_collection.len() - start_bottles as usize)
        ..(bottle_song_collection.len() - start_bottles as usize + (take_down as usize))]
        .join("\n\n")
}
